<a href="https://colab.research.google.com/github/georgegiannakidis/uhart-ms-prep/blob/main/Week1_Day1_NumPy_Starter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🎓 Week 1 — Day 1: NumPy Essentials
### UHart MS CS Pre-Arrival Prep · George · 7:00–8:30 PM

---

**Tonight's structure:**
- `7:00–7:05` → Quick setup & goals
- `7:05–7:55` → Learn NumPy: arrays, slicing, broadcasting, matrix ops
- `7:55–8:20` → 10 practice exercises
- `8:20–8:30` → Write 3 key takeaways + commit to GitHub

> 💡 **Watch first:** [Learn NumPy in 40 Minutes - Python NumPy Tutorial
)](https://www.youtube.com/watch?v=zI5ducyfyNc) — then come back and run this notebook.

---
## 📦 Setup

In [ ]:
import numpy as np
print(f'NumPy version: {np.__version__}')
print('✅ NumPy imported successfully!')

NumPy version: 2.0.2
✅ NumPy imported successfully!


---
## 1️⃣ Creating Arrays

NumPy's core object is the **ndarray** (n-dimensional array). It's like a Python list, but:
- All elements must be the **same type**
- It's **much faster** for math operations
- It supports **vectorized operations** (no for-loops needed)

In [ ]:
# 1D array (vector)
a = np.array([1, 2, 3, 4, 5])
print('1D array:', a)
print('Shape:', a.shape)       # (5,) means 5 elements
print('Data type:', a.dtype)   # int64 by default

1D array: [1 2 3 4 5]
Shape: (5,)
Data type: int64


In [ ]:
# 2D array (matrix)
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print('2D array:\n', b)
print('Shape:', b.shape)   # (2, 3) means 2 rows, 3 cols
print('ndim:', b.ndim)     # number of dimensions

2D array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
ndim: 2


In [ ]:
# Useful array creation shortcuts
print('zeros:', np.zeros((3, 3)))          # 3x3 matrix of 0s
print()
print('ones:', np.ones((2, 4)))            # 2x4 matrix of 1s
print()
print('arange:', np.arange(0, 10, 2))      # [0, 2, 4, 6, 8]
print()
print('linspace:', np.linspace(0, 1, 5))   # 5 evenly spaced values 0→1
print()
print('random:', np.random.rand(2, 3))     # 2x3 random floats [0,1)

zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

arange: [0 2 4 6 8]

linspace: [0.   0.25 0.5  0.75 1.  ]

random: [[0.36179669 0.11207987 0.23641389]
 [0.87440974 0.84423487 0.90874616]]


---
## 2️⃣ Indexing & Slicing

Slicing syntax: `array[start:stop:step]`

For 2D: `array[row, col]`

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])

print('First element:', arr[0])         # 10
print('Last element:', arr[-1])         # 60
print('First 3:', arr[:3])             # [10 20 30]
print('Last 2:', arr[-2:])             # [50 60]
print('Every other:', arr[::2])        # [10 30 50]
print('Reversed:', arr[::-1])          # [60 50 40 30 20 10]

First element: 10
Last element: 60
First 3: [10 20 30]
Last 2: [50 60]
Every other: [10 30 50]
Reversed: [60 50 40 30 20 10]


In [ ]:
# 2D indexing - this is critical for ML (datasets are 2D!)
matrix = np.array([[1,  2,  3,  4],
                   [5,  6,  7,  8],
                   [9, 10, 11, 12]])

print('Element at row 1, col 2:', matrix[1, 2])    # 7
print('Entire first row:', matrix[0, :])           # [1 2 3 4]
print('Entire second col:', matrix[:, 1])          # [2 6 10]
print('Submatrix (rows 0-1, cols 1-2):\n', matrix[:2, 1:3])  # 2x2

Element at row 1, col 2: 7
Entire first row: [1 2 3 4]
Entire second col: [ 2  6 10]
Submatrix (rows 0-1, cols 1-2):
 [[2 3]
 [6 7]]


---
## 3️⃣ Math Operations & Broadcasting

**Broadcasting** = NumPy automatically stretches smaller arrays to match larger ones for element-wise operations. No for-loops needed!

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print('Addition:', a + b)          # [11 22 33 44]
print('Multiply:', a * b)          # [10 40 90 160]
print('Power:', a ** 2)            # [1 4 9 16]
print('Scalar multiply:', a * 5)   # [5 10 15 20]  ← broadcasting!

Addition: [11 22 33 44]
Multiply: [ 10  40  90 160]
Power: [ 1  4  9 16]
Scalar multiply: [ 5 10 15 20]


In [ ]:
# Stats operations — used constantly in ML
data = np.array([4, 7, 13, 2, 9, 1, 6, 8, 3, 5])

print('Mean:', np.mean(data))       # average
print('Median:', np.median(data))   # middle value
print('Std dev:', np.std(data))     # spread
print('Min:', np.min(data))
print('Max:', np.max(data))
print('Sum:', np.sum(data))
print('ArgMax:', np.argmax(data))   # INDEX of the max value

Mean: 5.8
Median: 5.5
Std dev: 3.4292856398964497
Min: 1
Max: 13
Sum: 58
ArgMax: 2


---
## 4️⃣ Reshaping & Transposing

`reshape()` changes the shape without changing the data. Critical for feeding data into ML models.

In [ ]:
arr = np.arange(12)  # [0, 1, 2, ..., 11]
print('Original:', arr, '| Shape:', arr.shape)

reshaped = arr.reshape(3, 4)  # 3 rows, 4 cols
print('Reshaped (3x4):\n', reshaped)

reshaped2 = arr.reshape(2, 6)  # 2 rows, 6 cols
print('Reshaped (2x6):\n', reshaped2)

# -1 means "figure it out automatically"
auto_reshaped = arr.reshape(4, -1)  # 4 rows, NumPy figures out cols
print('Auto-reshaped (4x?):\n', auto_reshaped)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11] | Shape: (12,)
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped (2x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Auto-reshaped (4x?):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# Transpose — flips rows and cols (used heavily in linear algebra)
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print('Original (2x3):\n', m)
print('Transposed (3x2):\n', m.T)

Original (2x3):
 [[1 2 3]
 [4 5 6]]
Transposed (3x2):
 [[1 4]
 [2 5]
 [3 6]]


---
## 5️⃣ Linear Algebra (ML Foundation)

These operations appear in almost every ML algorithm under the hood.

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Dot product / Matrix multiplication
print('Matrix multiply (A @ B):\n', A @ B)
# Same as np.dot(A, B)

# Determinant
print('Determinant of A:', np.linalg.det(A))

# Inverse
print('Inverse of A:\n', np.linalg.inv(A))

# Eigenvalues & eigenvectors (used in PCA — Week 7!)
eigenvalues, eigenvectors = np.linalg.eig(A)
print('Eigenvalues:', eigenvalues)
print('Eigenvectors:\n', eigenvectors)

---
## 6️⃣ Boolean Masking & Fancy Indexing

Used constantly in ML for filtering datasets.

In [ ]:
scores = np.array([85, 42, 91, 67, 78, 55, 95, 33, 88, 72])

# Boolean mask — which students passed (>=70)?
passed = scores >= 70
print('Pass mask:', passed)
print('Passing scores:', scores[passed])   # fancy indexing with boolean
print('Number who passed:', np.sum(passed))
print('Pass rate:', np.mean(passed) * 100, '%')

In [ ]:
# np.where — like Excel IF()
grades = np.where(scores >= 70, 'Pass', 'Fail')
print('Grades:', grades)

---
## 🏋️ Practice Exercises (7:55–8:20 PM)

Try to solve each one **without looking at the hints**. Check the hint only if you're stuck after 3 minutes.

> ⏱️ **Target:** 12 minutes for all 10. That's ~70 seconds per exercise.

In [ ]:
# ── Exercise 1 ──────────────────────────────────────────────────
# Create a 4x4 identity matrix (1s on diagonal, 0s elsewhere)
# Hint: np.eye()

# YOUR CODE HERE
result = np.eye(4)
print(result)

# Expected output:
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# ── Exercise 2 ──────────────────────────────────────────────────
# Create an array of 20 evenly spaced numbers between 0 and 5 (inclusive)
# Then compute its mean and standard deviation
# Hint: np.linspace()

result = np.linspace(0, 5, 20)
print(result)
print('Mean:', np.mean(result))
print('Std dev:', np.std(result))

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
Mean: 2.5
Std dev: 1.51744244666721


In [ ]:
# ── Exercise 3 ──────────────────────────────────────────────────
# Given the matrix below, extract the 2nd column (index 1)
m = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print(m[:, 1])
# Expected: [20, 50, 80]

[20 50 80]


In [ ]:
# ── Exercise 4 ──────────────────────────────────────────────────
# Reshape the array [1..24] into a 3D array of shape (2, 3, 4)
# Then print its shape

# YOUR CODE HERE
arr = np.arange(1, 25, 1)
print(arr)
print(arr.shape)
result = arr.reshape(2, 3, 4)
print(result.shape)
# Expected shape: (2, 3, 4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(24,)
(2, 3, 4)


In [ ]:
# ── Exercise 5 ──────────────────────────────────────────────────
# Normalize this array so all values are between 0 and 1
# Formula: (x - min) / (max - min)
raw = np.array([2, 8, 14, 5, 19, 3, 11])

# YOUR CODE HERE
normalized = (raw - raw.min()) / (raw.max() - raw.min())
print(normalized)
# Expected: values all between 0.0 and 1.0

[0.         0.35294118 0.70588235 0.17647059 1.         0.05882353
 0.52941176]


In [ ]:
# ── Exercise 6 ──────────────────────────────────────────────────
# Stack these two arrays VERTICALLY (one on top of the other)
# Hint: np.vstack()
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# YOUR CODE HERE
result = np.vstack((x, y))
print(result)
# Expected:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [ ]:
# ── Exercise 7 ──────────────────────────────────────────────────
# Find the indices of the top 3 highest values in this array
# Hint: np.argsort() — think about direction
grades = np.array([72, 88, 55, 95, 61, 79, 91, 83, 68, 77])

# YOUR CODE HERE
sort = np.argsort(grades)
top3 = sort[-3:]
print(top3)

# Expected indices of the 3 highest values (order may vary)

[1 6 3]


In [ ]:
# ── Exercise 8 ──────────────────────────────────────────────────
# Generate a 5x5 matrix of random integers between 1 and 100
# Then compute the sum of each ROW (axis=1)
# Hint: np.random.randint(), .sum(axis=1)

# YOUR CODE HERE
matrix = np.random.randint(1, 101, (5, 5))
print(matrix)
row_sums = matrix.sum(axis=1)
print('Row Sum:', row_sums)

[[ 3 60 83 79 94]
 [92 20 50 43 34]
 [51 67  4 23 10]
 [93 72  9  5 95]
 [64 99 16 40 84]]
Row Sum: [319 239 155 274 303]


In [ ]:
# ── Exercise 9 ──────────────────────────────────────────────────
# Compute the dot product of these two vectors manually, then verify with np.dot()
# Dot product: multiply element-wise, then sum
v1 = np.array([1, 3, 5])
v2 = np.array([2, 4, 6])

# Manual: 1*2 + 3*4 + 5*6 = ?
manual_dot = 44  # replace None with your calculation
numpy_dot  = np.dot(v1, v2)  # use np.dot()

print('Manual:', manual_dot)
print('NumPy:', numpy_dot)
print('Match:', manual_dot == numpy_dot)

Manual: 44
NumPy: 44
Match: True


In [41]:
# ── Exercise 10 ──────────────────────────────────────────────────
# BONUS — GRC connection exercise!
#
# You're a GRC analyst. You have CVSS vulnerability scores for 8 systems.
# Critical = score >= 9.0 | High = 7.0–8.9 | Medium = 4.0–6.9
#
# Task: Using NumPy only (no loops!):
# 1. Count how many systems are Critical
# 2. Count how many are High
# 3. Print the average score of Critical systems only

cvss_scores = np.array([9.8, 7.2, 4.5, 9.1, 6.8, 8.5, 9.3, 3.2])
systems     = np.array(['WebApp', 'DB', 'API', 'Auth', 'Cache', 'LB', 'VPN', 'Monitor'])

# YOUR CODE HERE
critical = cvss_scores >= 9.0
high = (cvss_scores >= 7.0) & (cvss_scores < 9.0)
print('1. Critical:', np.sum(critical))
print('2. High:', np.sum(high))
print('3. Average of Critical:', np.mean(cvss_scores[critical]))

1. Critical: 3
2. High: 2
3. Average of Critical: 9.4


In [43]:
# 🏁 Quick self-check — run this cell to verify you understood the basics
import numpy as np

checks = {
    'Can create 1D and 2D arrays': True,       # True or False
    'Understand .shape and .dtype': True,
    'Can slice rows and columns': True,
    'Understand broadcasting': True,
    'Can use boolean masking': True,
    'Know np.dot() for matrix multiply': True,
    'Can reshape arrays': True,
}

# Replace None with True or False for each
for topic, status in checks.items():
    if status is None:
        print(f'⬜ (not rated) — {topic}')
    elif status:
        print(f'✅ {topic}')
    else:
        print(f'🔁 REVIEW NEEDED — {topic}')

✅ Can create 1D and 2D arrays
✅ Understand .shape and .dtype
✅ Can slice rows and columns
✅ Understand broadcasting
✅ Can use boolean masking
✅ Know np.dot() for matrix multiply
✅ Can reshape arrays


---
## 📋 Exercise Answer Key

**Only look after you've tried each exercise!**

Expand the code cells below when you're ready to check.

In [ ]:
# ANSWERS — run only after attempting all exercises!
import numpy as np

# Ex 1
print('Ex 1:', np.eye(4))

# Ex 2
arr2 = np.linspace(0, 5, 20)
print(f'Ex 2: mean={np.mean(arr2):.2f}, std={np.std(arr2):.2f}')

# Ex 3
m = np.array([[10,20,30],[40,50,60],[70,80,90]])
print('Ex 3:', m[:, 1])

# Ex 4
arr4 = np.arange(1, 25).reshape(2, 3, 4)
print('Ex 4 shape:', arr4.shape)

# Ex 5
raw = np.array([2, 8, 14, 5, 19, 3, 11])
normalized = (raw - raw.min()) / (raw.max() - raw.min())
print('Ex 5:', np.round(normalized, 2))

# Ex 6
x, y = np.array([1,2,3]), np.array([4,5,6])
print('Ex 6:\n', np.vstack([x, y]))

# Ex 7
grades = np.array([72, 88, 55, 95, 61, 79, 91, 83, 68, 77])
top3_indices = np.argsort(grades)[-3:]
print('Ex 7 top 3 indices:', top3_indices, '→ values:', grades[top3_indices])

# Ex 8
np.random.seed(42)
mat = np.random.randint(1, 101, (5, 5))
print('Ex 8 row sums:', mat.sum(axis=1))

# Ex 9
v1, v2 = np.array([1,3,5]), np.array([2,4,6])
print('Ex 9:', np.dot(v1, v2))   # 1*2 + 3*4 + 5*6 = 44

# Ex 10 (GRC bonus)
cvss = np.array([9.8, 7.2, 4.5, 9.1, 6.8, 8.5, 9.3, 3.2])
systems = np.array(['WebApp','DB','API','Auth','Cache','LB','VPN','Monitor'])
critical = cvss >= 9.0
high = (cvss >= 7.0) & (cvss < 9.0)
print(f'Ex 10: Critical={np.sum(critical)}, High={np.sum(high)}, Avg critical CVSS={np.mean(cvss[critical]):.1f}')